### Deploy Server ###
spring:
  datasource:
    url: ENC(8RGjgKwqoWxPXWWtozKImfcNo5GMUnCIMYvONc61FsNmKNqlVEmHnXVsHIEQBl9Ld7a/RJUCrSHzp7QxRKD0ldDBJju/8s6c)
    username: ENC(IYZiiPFZ/d7XM0OxII/y5ZjgTPU7eKRJ)
    password: ENC(tCx5PtshhUwYLTDIrXuItttIEB671nLL)
  ### Spring Security ###
  security:
    user:
      name: ENC(63WZpy9CngN/4ZPp134a4A==)
      password: ENC(Puc4Y8EdmHM1JCno/VQDrizi3Eq19/noW2lHNrEMtr5hjAtpQ5JkhNwnio5WboBa6kHTQOAq/sacPRQM39pIGQdNWKnQz1Ta)
      roles: ENC(yio+s1lOf2YcthENx1s+dg==)
### KakaoMap Api Key ###
kakao:
  map:
    apiKey: ENC(aWaJf4fwj6iqQ6yWO6EJ1dWIgEQ/0qNAsVUMlxODnZ+TAUaj+/+o8WcMHjfdIk9SzNOwqWMLs1I=)

### jasyptStringEncoder ###
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
